### ISSUE TITLE
Draco mesh compression (settings) creates artifacts when normal mapped, nice with gltf-pipeline

### ISSUE THREAD

**Issue by Rayfoundry** [facebookincubator/FBX2glTF#101]
Please check [https://github.com/donmccurdy/three-gltf-viewer/issues/92](https://github.com/donmccurdy/three-gltf-viewer/issues/92).

Looks like the draco compression settings used by FBX2GLTF are a bit too aggressive? Same file displays fine when run through gltf-pipeline from cesium.

**Comment by zellski** [comment]
Peculiar. The gltf-pipeline default settings are very similar to mine. They use `compressionLevel` 7 where I use 5, but we both use 10 bits for normals. They use 12 bits for uv coords, I use 10... 

Another difference is that I haven't bumped Draco releases in a while.

I'll add configurable compression settings and bump to latest release, and you can try again and see if the artefacts remain. If so we can see if there's anything else weird going on.

**Comment by zellski** [comment]
@Rayfoundry With https://github.com/facebookincubator/FBX2glTF/commit/d3f9a269ba90659ea0a0e61521128f2b806e01db just now, you can tweak Draco settings. Would you be willing to try your model again, and maybe give normals and/or uv some extra bits?

**Comment by Rayfoundry** [comment]
@zellski Checking now.

**Comment by Rayfoundry** [comment]
@zellski Hey Pär, that fixed it. All looking good with the recent changes. Took me a while to build from C++, get the old FBX SDK etc. - but well worth the effort. Thanks for updating this!
