### ISSUE TITLE
Windows Binary Confusion

### ISSUE THREAD

**Issue by tylocook** [facebookincubator/FBX2glTF#102]
When I run FBX2glTF-windows-x64.exe from the command line, it prompts me to install an FBX Converter x64 2013.3.

After installing it, nothing happens (other than the fact that I know have the Autodesk FBX Converter installed).

Is there something I am missing after doing this? 

Attempting to run FBX2glTF-windows-x64.exe with arguments produces the same results.

**Comment by zellski** [comment]
Hey @tylocook --

I just can't replicate this. I don't understand why it's happening. I honestly know very little about the specific details of Windows development.

When you run the binary, does it literally display a popup of some kind? Or is the output urging you to install the converter on the console?

**Comment by tylocook** [comment]
Disregard, I was opening a very similarly named application and completely missed that I was not opening the proper one.
