### ISSUE TITLE
Colors appear brighter

### ISSUE THREAD

**Issue by TSF404** [facebookincubator/FBX2glTF#110]
I have recently created a simple unlit object within cinema 4D.

![image](https://user-images.githubusercontent.com/10264833/41573005-ec4c3fe4-73bd-11e8-9059-4d578714fcd4.png)

I then exported it to FBX and converted the FBX to a gltf.

I ensured that the colors in the gltf file still matched the one in the original project. Let's take the paddle as an example. Within the editor, the paddle's color is 192,151,112.

![image](https://user-images.githubusercontent.com/10264833/41573192-cdb437f2-73be-11e8-878e-6d9683978579.png)

The color for the paddle in the gltf file is represented as 0.755, 0.595, 0.443 which equals 192, 155, 112 (multiplied by 255), which matches the color settings in the editor.
![image](https://user-images.githubusercontent.com/10264833/41573238-0ab5b432-73bf-11e8-9d4e-ee1f7e8c0b31.png)

I then converted it to a KHR unlit glb via: 
https://glb-packer.glitch.me/

When I put it into facebook, all the colors appear brighter.
![image](https://user-images.githubusercontent.com/10264833/41573388-c6db39fc-73bf-11e8-8df1-5b884bd54fe2.png)

![image](https://user-images.githubusercontent.com/10264833/41573506-50e4aaf2-73c0-11e8-893e-280cb9f16d57.png)

I've also tried displaying the gltf file in online gltf viewers. They all seem to render the colors brighter.

![image](https://user-images.githubusercontent.com/10264833/41573542-87c453a6-73c0-11e8-91f8-84dbb50ba536.png)

I'm wondering what might have caused this and how this can be resolved so I can ensure that the colors on the gltf file match the output colors 100%.

I've attached the source files.

Thank you

[paddlepop_issue.zip](https://github.com/facebookincubator/FBX2glTF/files/2113675/paddlepop_issue.zip)

**Comment by zellski** [comment]
Closing this for now.
