### ISSUE TITLE
Is there a posiblility to use this converter by code?

### ISSUE THREAD

**Issue by Neuxxx** [facebookincubator/FBX2glTF#112]
hi, 
for my project it would be very helpfull to implement the converter direktly as dll or NuGet.
Do you see for future releases a posebility to provide your converter as lib as SDK ?

This would be very great. At this moment your projekt is maybe the best working fbx-to-gltf converter!

**Comment by zellski** [comment]
Hi there, That is a nice idea. I will add it to the list of feature requests!

**Comment by zellski** [comment]
This is done & will be in the next release.
