### ISSUE TITLE
Support for reading physical material in FBX generated from 3ds Max

### ISSUE THREAD

**Issue by gopikrishnachaganti** [facebookincubator/FBX2glTF#116]
I am trying to convert FBX which is created using 3ds max using physical material to GLTF format. FBX2glTF is unable to understand the physical material and unable to extract & associate the textures around it. also metalness & roughness support required. 

Please let me know if this has been implemented and how to use it. 
Thanks,
Gopikrishna

**Comment by zellski** [comment]
Tracking this work in https://github.com/facebookincubator/FBX2glTF/issues/111#issuecomment-402763068.
