### ISSUE TITLE
FBX2glTF not working for multi material Stingray PBS for FBX created in Maya & 3dsMax

### ISSUE THREAD

**Issue by gopikrishnachaganti** [facebookincubator/FBX2glTF#117]
We have multi materials used in models. when exported FBX with Maya & 3dsmax and then trying to convert into gltf format, the textures are messing up due merging textures and gltf output is loosing the arm textures. 

do we have any fix for the same?

**Comment by zellski** [comment]
Hey there. I need more information to be able to fix this. What do you mean by textures being "messed up"? Did you export both from 3ds Max and Maya? Did you get the same error in both exports? What's special about "arm" textures? There's nothing I can really do with such vague descriptions.

The best thing would be if you can supply the FBX file(s) that are not converting. If you aren't able to hand those out, can you reduce the problem to a simple, small test case, and upload that?

Thanks!
