### ISSUE TITLE
npm usage example fails

### ISSUE THREAD

**Issue by iambumblehead** [facebookincubator/FBX2glTF#118]
The usage [example with the npm package][0] fails,
```javascript
const convert = require('fbx2gltf');
convert('path/to/some.fbx', 'path/to/target.glb', ['--khr-materials-common']).then(
  destPath => {
    // yay, do what we will with our shiny new GLB file!
  },
  error => {
    // ack, conversion failed: inspect 'error' for details
  }
);
```

The error callback is called when the example is followed. Replacing `['--khr-materials-common']` with `[]` allows the example to work. 

[0]: https://www.npmjs.com/package/fbx2gltf

**Comment by zellski** [comment]
Thank you! Fixed in https://github.com/facebookincubator/FBX2glTF/commit/2fc254ed79331ae5410204411eb8b3c5b4dd2ef5.
