### ISSUE TITLE
Accessors missing name

### ISSUE THREAD

**Issue by ox** [facebookincubator/FBX2glTF#120]
I am trying to convert an FBX file with many shape keys. While the gltf has the correct animation path (`weights`) and the correct number of targets, the accessors themselves are missing the shape key names. This is valuable information when I want to find blend shapes by name and not index. I noticed that fbx2gltf does not store the name in it's `AccessorData` struct, nor does it handle it in `fbx2raw.cpp`. Ideally both the `input` and `output` accessors for each animated primitive's targets should share the same name.

I think the work involved, so far, is at least:
- add name to `TargetShape`
- extract name in `extractChannels`

**Comment by ox** [comment]
I got the blendshape keys to copy over to that accessor names with [this gist](https://gist.github.com/ox/5b0a57d2c58156a799d9df603272d931). Should I make a PR?

**Comment by zellski** [comment]
Hey @ox, thanks for the report & fix! Sure, yes, please go ahead and make a PR (note that you will need to accept a Facebook agreement to do so). Maybe delete that fmt::printf() line? Unless it can be summarised at the end, wrapped around if (verboseOutput)...
