### ISSUE TITLE
Vertex Cache Animations

### ISSUE THREAD

**Issue by maximcapra** [facebookincubator/FBX2glTF#123]
I guess vertex caches (.mc or .pc2) are not supported in the conversion process? I could not find a way to get these animations from my fbx file into the gltf file. This would be a great feature!

**Comment by zellski** [comment]
Hey @maximcapra, thanks for posting! I hadn't come across any mention of vertex cache animations before. It looks like it's essentially a high bandwidth stream of positional deltas for (potentially) every single vertex in a mesh, for every keyframe?

If that's a correct summary, then unfortunately I don't think glTF is realistically able to express it. The format includes morph targets (blend shapes) and it includes rigged/skeletal animation. Neither is able to manipulate vertices individually like this.

I will close this for now. If, one day, someone introduces a glTF extension for this animation type, we'll revisit support in FBX2glTF.

**Comment by maximcapra** [comment]
I see, thanks for your reply!

I did some more research after posting on your git, I wasn't aware of the
lack of vertex cache support in gltf. Your summary was correct. I am coming
from VFX and file sizes and performance is not so much an issue for me, but
it makes total sense. On the other hand this would be the cleanest way to
get some really complex animation from a DCC to the web ... well, I will
find another way with bones and skinning ...

Thanks,
Phil

DI(FH) Philipp Zaufel
+43 676 44 617 08

philipp@maximcapra.com
maximcapra.com
