### ISSUE TITLE
Output files are incredibly small

### ISSUE THREAD

**Issue by mikebourbeauart** [facebookincubator/FBX2glTF#124]
Not that big of a deal but the converted files always much smaller than say a converted glTF download from sketchfab. I'm using Maya so maybe it's a unit issue? Maybe adding in a -unit flag so we can say whether or not the file is in mm, cm, m etc.

**Comment by zellski** [comment]
The FBX file itself is supposed to contain unit information, but it doesn't always appear to be accurate, maybe depending on the exporter. As far as I'm aware, FBX2glTF does the right thing with the information it has available. That's not to say a command line override couldn't be worthwhile, though.

**Comment by zellski** [comment]
Closing this as an enhancement, as there's no current plans to add unit translation. If someone feels it's a demonstrably bug, please reopen.
