### ISSUE TITLE
Crashed on Windows

### ISSUE THREAD

**Issue by Siccity** [facebookincubator/FBX2glTF#127]
Trying to convert an fbx.
Getting the error
```
Warning: node /RootNode/3D View: {3D} uses unsupported transform inheritance type 'eInheritRrSs
```
Exported from Revit

**Comment by zellski** [comment]
This isn't really a crash; the program will continue & should generate a .glb / .gltf. If it did crash, something else is wrong.

As for the warning, I'm afraid there's nothing the program can do about this. It's something that can appear in FBX files that glTF can't represent. Quite often it's harmless in practice, though.
