### ISSUE TITLE
Exported GLB doesn't work in ThreeJS GLTFLoader

### ISSUE THREAD

**Issue by robertlong** [facebookincubator/FBX2glTF#13]
The exported `.glb` files don't seem to work in anything that uses ThreeJS GLTFLoader. Babylon.JS seems to work fine. Trying to hunt down the root cause, but could use some help.

Here's a test model with the `.glb` as well as source assets (don't mind the weird UV mapping).

[Head.zip](https://github.com/facebookincubator/FBX2glTF/files/1399980/Head.zip)

**Comment by robertlong** [comment]
Looks like it's an issue in ThreeJS GLTFLoader having to do with handling transparency. I'll move the discussion over there.

**Comment by zellski** [comment]
@robertlong -- actually, I think three.js is doing the right thing here.

If you inspect Head.fbx, you see that AvatarMaterial has Opacity 0.
In the generated .glb, that becomes a baseColorFactor with a 0 alpha component.

Perhaps BabylonJS ignores that value, and therefore it seems like it works?

If I manually bump opacity up in the three.js node hierarchy, the head shows up:
<img width="530" alt="screenshot 2017-10-21 22 22 09" src="https://user-images.githubusercontent.com/714167/31858543-3a0235a8-b6af-11e7-9692-da214bfc7322.png">

I'm not sure what you're using to create the FBX, but looking at the transparency/opacity setting might be worthwhile.
