### ISSUE TITLE
Transcribe FBX Custom Properties to into a glTF extras object

### ISSUE THREAD

**Issue by zellski** [facebookincubator/FBX2glTF#130]
FBX allows for custom, typed key/value properties on any `FbxObject`. Most of these could be mapped to a glTF object, and there they could be transcribed into extras fields, perhaps something like:

```
"nodes": [{
  "name": "RootNode",
  "children": [ 1 ],
  "extras": {
    "fromFBX": {
      "userProperties": {
        "myCustomProperty": {
          "value": "13",
          "type": "FbxUShortDT"
        }
      }
    }
  }
}, { ... }]
```
where we just picked a node as an example; could be just about any glTF object. The type names are taken from [here](https://help.autodesk.com/view/FBX/2017/ENU/?guid=__cpp_ref_fbxdatatypes_8h_html) and further reading on properties can be found [here](https://help.autodesk.com/view/FBX/2017/ENU/?guid=__cpp_ref_class_fbx_property_html).

**Comment by zellski** [comment]
Great news! Quick work. I haven't seen the code yet obviously, but:
- If the output in the glTF is **at all** verbose, let's wrap the output in an opt-in command line switch.
- I have another refactor on the way; you can see its current diff against trunk [here](https://github.com/facebookincubator/FBX2glTF/compare/zell_cleanup_2). If you think that's going to cause a lot of merge conflicts, let's make sure you get yours in first so you don't have to figure out all the little things I changed all over the place.

**Comment by EscapeZero** [comment]
Output looks like this:
```
"fromFBX": {
    "userProperties": {
        "currentUVSet": {
            "type": "eFbxString",
            "value": "map1"
        },
        "fidId": {
            "type": "eFbxInt",
            "value": 131
        },
        "blah": {
            "type": "eFbxBool",
            "value": 0
        },
        "ftest": {
            "type": "eFbxDouble",
            "value": 1.33333
        },
        "ded": {
            "type": "eFbxDouble3",
            "value": [
                0.0,
                0.0,
                0.0
            ]
        }
    }
}
```
`currentUVSet` only "garbage" I have found so to speak. Maya adds that to every mesh I believe.

**Comment by zellski** [comment]
Many thanks for the pull! I will wrap it in --user-properties (and --no-user-properties), and I think the default should be 'on'. It's possible someone out there will get cranky that behaviour changes from minor version to minor version, but this is just metadata, it has no effect on the model itself... and we're in beta. So I feel pretty okay with that.
