### ISSUE TITLE
FBX to GLB convertion with external texture files

### ISSUE THREAD

**Issue by EtagiBI** [facebookincubator/FBX2glTF#136]
As far as I see, there's no option to convert FBX files to GLB files with external texture files. Is it possible to add this feature?

**Comment by zellski** [comment]
What do you mean by external? Referenced by URI? Do you mean FBX2glTF would upload textures somewhere, or that the user would supply URIs for each texture on the command line?

**Comment by EtagiBI** [comment]
By "external" I mean individual image files that are not packed into GLB. 
For instance, I have an FBX model with individual image files (not embedded). I would like to convert my FBX to GLB without breaking references to image files.

**Comment by zellski** [comment]
Oh, that should certainly work. It is quite sensitive to filename matching, though. Where are the texture files located? Also make sure to run the binary with -v flag and see if there are any reports on textures found or missing. Feel free to paste the output here. Finally, it matters what platform you are on - Windows?

**Comment by kkakosim** [comment]
It does work w external textures. Co located with fbx and conventional naming.

**Comment by zellski** [comment]
@EtagiBI Any luck?

**Comment by EtagiBI** [comment]
Oh, sorry, I forgot to close the issue.

We've decided not to use FBX due to various issues with export. It's easier to find The Holy Grail than to export valid FBX with external textures from 3DS Max. 

Thanks for your attention to my question!

**Comment by zellski** [comment]
I don't blame you. Good luck! :-)
