### ISSUE TITLE
Provide a alternate search folder

### ISSUE THREAD

**Issue by fire** [facebookincubator/FBX2glTF#144]
Hi,

Is it possible to provide an alternate search folder. The importer I'm calling FBX2glTF first exports to a .import folder, but the fbx file is in a regular location.

I'm looking for something like:

bool LoadFBXFile(RawModel &raw, const char *fbxFileName, const char *textureExtensions, const char *alternateSearchFolder);

So that the glb / gltf can find the original location's .fbm folder.

Is there a better design than just creating a new function for it?

Oh the original problem is that the gltf file cannot find the textures because the gltf file is written to the .import folder and the fbm folder is placed near the fbx.

**Comment by zellski** [comment]
This would be a good extension to the API. There's very little spare time for development on this project at the moment, though, I'm afraid. I'm focusing on bug reports. Pull requests are always welcome, of course.

**Comment by fire** [comment]
Closing old issues.
