### ISSUE TITLE
Building on Mac OS

### ISSUE THREAD

**Issue by mariel-pettee** [facebookincubator/FBX2glTF#146]
Hi, I'm running into an error when running the cmake command on Mac OS Sierra (10.12.6) with CMake 3.12.1. I've tried with both Autodesk FBX SDK version 2018.1.1 and 2019.2 with no success. 

```
[ 88%] Building CXX object CMakeFiles/libFBX2glTF.dir/src/utils/String_Utils.cpp.o
/Users/mnp3/Google_Drive/AI/code/FBX2glTF/src/utils/File_Utils.cpp:187:88: error: redefinition of default argument
    bool CopyFile(const std::string &srcFilename, const std::string &dstFilename, bool createPath = false) {
                                                                                       ^            ~~~~~
/Users/mnp3/Google_Drive/AI/code/FBX2glTF/src/utils/File_Utils.hpp:27:88: note: previous definition is here
    bool CopyFile(const std::string &srcFilename, const std::string &dstFilename, bool createPath = false);
                                                                                       ^            ~~~~~
```

Any help would be much appreciated! Thanks.

**Comment by zellski** [comment]
Hey @mariel-pettee, this seems to be my fault. Not sure why it didn't get caught earlier.

I believe I fixed it in https://github.com/facebookincubator/FBX2glTF/commit/7374bcf34f5015eec4615cdcbe0e2404131f38e5; can you pull and try again?

**Comment by mariel-pettee** [comment]
Thanks so much -- seems to have fixed the issue for me!

**Comment by zellski** [comment]
Great to hear. I intend to finally release 0.9.6 in the next few days and it's good to know it compiles everywhere.
