### ISSUE TITLE
Warning Message While Converting From FBX

### ISSUE THREAD

**Issue by Qusai-Azzam** [facebookincubator/FBX2glTF#151]
Warning: could not find a local image file for texture: Untitled_001.
Original filename: Nor.jpg
Warning: could not find a local image file for texture: Wingskin_001.
Original filename: Wingskin2.png
Warning: node /RootNode/Dragon_Mesh uses unsupported transform inheritance type 'eInheritRrSs'.
         (Further warnings of this type squelched.)

and the output doesn't contain any Pictures

**Comment by zellski** [comment]
Are there any files called `Nor.jpg` or `Wingskin2.png`? If so, where are they?

It's impossible for me to guess what might be going wrong without more information. Please give as much context as you can.
