### ISSUE TITLE
I converted a model and turned on Draco compression and read the model incorrectly in UV

### ISSUE THREAD

**Issue by gameatp** [facebookincubator/FBX2glTF#157]
![image](https://user-images.githubusercontent.com/4427058/51115619-bc261a80-1843-11e9-96f0-0fccf9fa3e3f.png)
[21003.zip](https://github.com/facebookincubator/FBX2glTF/files/2755302/21003.zip)

**Comment by gameatp** [comment]
[21003.zip](https://github.com/facebookincubator/FBX2glTF/files/2766691/21003.zip)
I found that maybe Google's Draco compressed data might have problems.

**Comment by gameatp** [comment]
> Hi @gameatp are you able to provide the FBX?

[21003.zip](https://github.com/facebookincubator/FBX2glTF/files/2766695/21003.zip)

**Comment by gameatp** [comment]
> > Hi @gameatp are you able to provide the FBX?
> 
> [21003.zip](https://github.com/facebookincubator/FBX2glTF/files/2766695/21003.zip)
> I found that maybe Google's Draco compressed data might have problems.

I found a problem with Draco compression, and I changed the code to work properly.

The second parameter of AddAttribute needs to fill in false and then pass

**Comment by zellski** [comment]
Hey –– I don't think the solution is quite this simple, but it's interesting that the mapping (which is controlled by that parameter) might be broken. I'd still like to look into this, so I'm going to reopen the issue.

**Comment by gameatp** [comment]
> Hey –– I don't think the solution is quite this simple, but it's interesting that the mapping (which is controlled by that parameter) might be broken. I'd still like to look into this, so I'm going to reopen the issue.

Oh, yes, we need to change a few places.

First:
![image](https://user-images.githubusercontent.com/4427058/52387698-3ace4a80-2ac6-11e9-8720-145248ab25e1.png)
Then:
![image](https://user-images.githubusercontent.com/4427058/52387726-49b4fd00-2ac6-11e9-925d-a4592d27eda6.png)
Last:
![image](https://user-images.githubusercontent.com/4427058/52387773-6f420680-2ac6-11e9-9638-ddc33769ff8d.png)

**Comment by zellski** [comment]
Hi @gameatp; I was able to take a look at this. I do not think the changes you're proposing are necessary. We have a very simple vertex<->attribute mapping in glTF, and I believe identity_mapping should be true. I think I fixed the real problem in https://github.com/facebookincubator/FBX2glTF/commit/e83d495fdc423809e4bbe164f74dedc49e0c53e0, which yields this result:
![image](https://user-images.githubusercontent.com/714167/53283112-30cb5f00-36f6-11e9-9746-3adb8cf560f1.png)

Would you give it a try yourself, and validate my result?

**Comment by gameatp** [comment]
> Hi @gameatp; I was able to take a look at this. I do not think the changes you're proposing are necessary. We have a very simple vertex<->attribute mapping in glTF, and I believe the `identity_mapping` argument to AddAttribute() should be true, the way I have it.
> 
> BUT, I think I fixed the actual underlying problem in [e83d495](https://github.com/facebookincubator/FBX2glTF/commit/e83d495fdc423809e4bbe164f74dedc49e0c53e0), which yields this result:
> ![image](https://user-images.githubusercontent.com/714167/53283112-30cb5f00-36f6-11e9-9746-3adb8cf560f1.png)
> 
> Would you give it a try yourself, and validate my result?

I just tried this. It's OK. You're right. Your method is better. Thank you.
