### ISSUE TITLE
Not finding assets

### ISSUE THREAD

**Issue by ran-j** [facebookincubator/FBX2glTF#161]
![image](https://user-images.githubusercontent.com/17410205/52607584-e6c4bc80-2e5d-11e9-8216-c6dc16f1c8c8.png)

But if you look at the folder

![image](https://user-images.githubusercontent.com/17410205/52607599-f80dc900-2e5d-11e9-846d-8dbd919b8c89.png)

all assets ar in.

To convert model `FBX2glTF.exe --draco --verbose yumeko.fbx`

**Comment by zellski** [comment]
Hi there, I believe this should be fixed in the next version. I hope to release it shortly.

**Comment by ran-j** [comment]
ok,  on linux works normaly
