### ISSUE TITLE
The color changes to one color

### ISSUE THREAD

**Issue by tokufxug** [facebookincubator/FBX2glTF#162]
Converting ASCII style FBX where two objects overlap to GLB.
Colors that were different individually are converted to one color.

Before FBX
 Image [http://tokufxug.sakura.ne.jp/fbx2glb/before_fbx.png](http://tokufxug.sakura.ne.jp/fbx2glb/before_fbx.png)
 Data [http://tokufxug.sakura.ne.jp/fbx2glb/data.fbx](http://tokufxug.sakura.ne.jp/fbx2glb/data.fbx)

Convert GLB
 Image [http://tokufxug.sakura.ne.jp/fbx2glb/after_glb.png](http://tokufxug.sakura.ne.jp/fbx2glb/after_glb.png)
 Data   [http://tokufxug.sakura.ne.jp/fbx2glb/data.glb](http://tokufxug.sakura.ne.jp/fbx2glb/data.glb)

FBX2glTF-windows-x64
OS: Windows 10 Pro 1803

**Comment by zellski** [comment]
Ah, it's because some of the older code still uses the logical material name to distinguish two materials from one another, even though they differ in other important ways. I will fix.

**Comment by tokufxug** [comment]
Thank you for considering the correction.
When is the release planned?

**Comment by zellski** [comment]
Fixed in https://github.com/facebookincubator/FBX2glTF/commit/a596073f0423635115ad9db42cd855a80b055ffd:

![image](https://user-images.githubusercontent.com/714167/53312675-d9023480-386a-11e9-8eef-e188b393178e.png)

I am hoping to get a new release out shortly. I can also quite easily create an interim version for you to use.

**Comment by tokufxug** [comment]
I'd like to get a provisional version.

**Comment by zellski** [comment]
Try going [here](https://dev.azure.com/parwinzell/FBX2glTF/_build/results?buildId=44&view=results) and clicking 'Artifacts' in the upper right corner. That should hopefully download ZIP file with all three platform builds. I am also attaching a Zip file with the Windows binary here.

[FBX2glTF-windows-x64.exe.zip](https://github.com/facebookincubator/FBX2glTF/files/2901684/FBX2glTF-windows-x64.exe.zip)

**Comment by tokufxug** [comment]
Thank you for creating.
It works without problems.
