### ISSUE TITLE
I turned fbx, turned on Draco compression and crash

### ISSUE THREAD

**Issue by gameatp** [facebookincubator/FBX2glTF#166]
Here is the FBX source file

[testmodel.zip](https://github.com/facebookincubator/FBX2glTF/files/2945831/testmodel.zip)

**Comment by zellski** [comment]
Hi... can't reproduce this. Can you please tell me which version of the tool you used (the 0.9.5 release, or a recent build, or did you build it yourself?) and ideally what the command looked like?

**Comment by gameatp** [comment]
> Hi... can't reproduce this. Can you please tell me which version of the tool you used (the 0.9.5 release, or a recent build, or did you build it yourself?) and ideally what the command looked like?

I compiled a version myself, as if the weight problem led to dividing by 0, and I solved it myself.

**Comment by zellski** [comment]
Oh right! OK, closing this then.
