### ISSUE TITLE
can't get uv1 texture coordinates of fbx

### ISSUE THREAD

**Issue by comsyspro** [facebookincubator/FBX2glTF#169]
**- This issue is detected for the releases from 0.9.1 to latest 0.9.5.**
**- The release 0.9.0 works fine**

**The error:**
I have a fbx model with uv0 and uv1 texture coordinates. After converting the fbx the converted gbl file uses only the uv0 texture coordinates and loses the uv1 texture coordinates of the original fbx file. So the gbl model uses only the uv0 coordinates of the fbx file for the wanted uv1.

>FBX2glTF-windows-x64.exe -i group001.fbx -o group -bv -k uv0 -k uv1 -k position -k normal -k color -k binormal

**So where could be the error?**

The same fbx model was imported in the three.js Editor and exported to a gbl model and here both uv0 and uv1 were exported correctly. Also the FBX2glTF release 0.9.0 works fine.

**So what went wrong with FBX2glTF conversion?**

Besides a small spelling mistake exists in the code when using the -k switch in the description of valid choices  it should be **binormal** instead of binormial.

**Comment by comsyspro** [comment]
I could answer myself.

**Comment by kevinshane** [comment]
hi, please re-open this issue, I have exactly the same problem when using latest 0.9.7 windows version, but uv2(uv1 aka lightmap channel) is correctly exported in 0.9.0 first release windows version. please tell me if I miss something important?
here is what I run in powershell
`.\FBX2glTF-windows-x64.exe -k uv0 -k uv1 -k position -k normal -k color -k binormal -i .\tab.fbx -o table -b -v`

**Comment by comsyspro** [comment]
Just try `--no-flip-v` parameter. This was my solution some month ago.
