### ISSUE TITLE
New binary builds/Can't check out code

### ISSUE THREAD

**Issue by jmo7** [facebookincubator/FBX2glTF#198]
Is there any chance  new release of a binary could be released for those of us who aren't build meisters

**Comment by jmo7** [comment]
I just tried to check out the code to take a look and I get an error message "Error downloading object: npm/tests/models/fromFacebook/Jon/jon_morph.fbx (4c2a5e8): Smudge error: Error downloading npm/tests/models/fromFacebook/Jon/jon_morph.fbx (4c2a5e85e167c1b9d91dbfe29a44cad80afab7f95a97f42c69a40dbd573265df): batch response: This repository is over its data quota. Purchase more data packs to restore access."

**Comment by jmo7** [comment]
More details: It turns out I can choose the download a zip option and it works. It's just when I try to git clone it I get the error message.

**Comment by zellski** [comment]
Aha. That makes sense, there's a quota on the LFS. I think I might just delete the SDK from the repository.

**Comment by zellski** [comment]
I've nuked the SDK from the checkout. The large asset files in npm/test still use LFS, though, unfortunately.

**Comment by etherlore** [comment]
Having the same issue. This seems to affect Forks as well, which means you can't clone those either. You can get around this by setting GIT_LFS_SKIP_SMUDGE=1, but that results in un-tracked files which means you can't rebase/merge with upstream.

**Comment by zellski** [comment]
We really can't have basic checkouts semi-randomly fail based on so many variables outside our control. I think I will splice the tests (which are always likely to require some largeish assets) of to another repo, or at minimum another branch, so 'master' can always be safely checked out. Although the branch thing could get annoying.

**Comment by zellski** [comment]
Should be fixed in https://github.com/facebookincubator/FBX2glTF/commit/43e3d054404222c84e23be1fdb5ddb6cf53d056f.
