### ISSUE TITLE
Images missing files. Only one image is exported.

### ISSUE THREAD

**Issue by roxlu** [facebookincubator/FBX2glTF#199]
I'm using Blender 2.8 to export a test scene to .fbx. Then I use FBX2glTF to convert the FBX into a GLTF file. Currenly the default GLTF exporter of Blender doesn't support linked collections correctly yet which is why I'm using FBX2glTF. 

A first try with FBX2glTF seemed to work great; but only after creating a scene with a couple of albedo textures I found out that the generated .gltf files from FBX2glTF only contain one image. 

I've attached the blender files and exported .gltf/bin files:

[Blender 2.8 files](https://github.com/facebookincubator/FBX2glTF/files/3226184/fbx-images-not-exporting.tar.gz)

[Generated GLTF files by FBX2glTF](https://github.com/facebookincubator/FBX2glTF/files/3226197/book-scene_out.tar.gz)

[Exported FBX from Blender 2.8](https://github.com/facebookincubator/FBX2glTF/files/3226217/book-scene.tar.gz)

When I import the generated .fbx from Blender, all textures are correctly loaded.

**Comment by zellski** [comment]
Hi @roxlu, thanks for your report!

I was able to convert the asset successfully after placing the two JPEGs (book-cover-1.jpg and book-cover-2.jpg) in the same directory as the FBX file, as you can [see here](https://gltf.insimo.com/vFpkADwXUmeO7DrXIObemycZj40ofUnFEaw6vcQ.yHrR6GUjPvsX0jNnIWTyxsCspUaCVDlSRWREdw).

I noticed that in book-scene_out.tar.gz you have one of the images named 'asset-book-cover.jpg', which would be meaningless to FBX2glTF. It can only match up textures if they have the same base name.

The sturdiest way to get textures converted is to embed them in the FBX itself. Then you don't have to manually ensure that filenames match up.

Does this solve your issue? Note also that I've rewritten a lot of the texture handling code. If you were testing with 0.9.5 (over a year old) it's possible you ran into some other bug as well.
