### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by gameatp** [facebookincubator/FBX2glTF#207]
![image](https://user-images.githubusercontent.com/4427058/59175307-a36a2880-8b87-11e9-9a48-99d5d3141545.png)

**Comment by zellski** [comment]
Yes... did you read the advice in the error message? CMake is now a second pass; the package manager Conan should be first to run.

**Comment by makovkins** [comment]
Build fails on Windows:

**conan install . -i build_release -s build_type=Release -e FBXSDK_SDKS=C:\Autodesk\FBX**
succeeded

**conan build . -bf build_release** 
fails with the following error:

conanfile.py: Running build()
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "D:/Work/PIK/FBX2glTF-master/build_release" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ERROR: conanfile.py: Error in build() method, line 32
        cmake.configure()
        ConanException: Error 1 while executing cd D:\Work\PIK\FBX2glTF-master\build_release && cmake -G "Visual Studio 15 2017 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DCMAKE_INSTALL_PREFIX="D:\Work\PIK\FBX2glTF-master\build_release\package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_MODULE_PATH="D:/Work/PIK/FBX2glTF-master/build_release" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DFBXSDK_SDKS="C:\Autodesk\FBX\" -Wno-dev D:\Work\PIK\FBX2glTF-master
