### ISSUE TITLE
FOV bug with EApertureMode::eHorizontal or EApertureMode::eVertical

### ISSUE THREAD

**Issue by C0lumbo** [facebookincubator/FBX2glTF#209]
In this snippet of code from Fbx2Raw.cpp

> 
>     case FbxCamera::EApertureMode::eHorizontal: {
>       fovx = pCamera->FieldOfViewX;
>       fovy = HFOV2VFOV(fovx, apertureRatio);
>       break;
>     }
>     case FbxCamera::EApertureMode::eVertical: {
>       fovy = pCamera->FieldOfViewY;
>       fovx = VFOV2HFOV(fovy, 1.0 / apertureRatio);
>       break;
> }

`pCamera->FieldOfViewX `and `pCamera->FieldOfViewY `are incorrect and should be replaced by `pCamera->FieldOfView`.

According to FBX docs, `FieldOfViewX`/`FieldOfViewY `:
> has meaning only when property ApertureMode equals eHorizAndVert.

(thank you for this project, btw, it's about 100x better than any FBX SDK docs/samples for figuring out how to extract useful information).

**Comment by zellski** [comment]
Thanks for the excellent report, the trivial fix is finally committed.
