### ISSUE TITLE
Bugs occur when using npm to convert fbx to gltf

### ISSUE THREAD

**Issue by HypnosNova** [facebookincubator/FBX2glTF#217]
Following steps:
1. yarn add fbx2gltf
2. write following code
![image](https://user-images.githubusercontent.com/7953802/62199481-25bbdf80-b3b6-11e9-915b-90b44f3e7a4c.png)
3. run the script and terminal shows:
![image](https://user-images.githubusercontent.com/7953802/62199542-3e2bfa00-b3b6-11e9-9aa2-35353c9a34f6.png)

It shows that if I convert fbx to gltf, the module won't create a dir which it needs automatically.
If I convert fbx to glb everything is OK.

Another bug is the fbx contains textures but if I use this script it will lose all the textures. But if I use FBX2glTF.exe and use cmd to convert models, everything is OK.

**Comment by zellski** [comment]
Hi @HypnosNova,  thanks for the report.

I see you filed this 14 hours ago, right after the release. But, I hadn't published the new release (0.9.6) to the public NPM repo at that point.

Could you upgrade your fbx2gltf dependency to 0.9.6 and see if the result is the same?

**Comment by HypnosNova** [comment]
@zellski Thanks you, I update to 0.9.6 right now and these two bugs are fixed.
