### ISSUE TITLE
npm package broken on Linux?

### ISSUE THREAD

**Issue by mramato** [facebookincubator/FBX2glTF#222]
The npm package seems to include a `FBX2glTF` linux binary without the executable bit set, so Node fails to actually run the converter.

**Comment by zellski** [comment]
Ugh. Something must've broken in my release script. I'll check. Thanks!

**Comment by zellski** [comment]
Same issue as the Linux build. Argh. Okay, I’ll buy WiFi on this plane and rerelease the package. Thanks for the poke!

**Comment by Pratyush1184** [comment]
Facing the same issue with the npm package version 0.9.7. The converter runs successfully with the version 0.9.5 though.

**Comment by zellski** [comment]
Very sorry for this delay. Please find 0.9.7-p1 published, hopefully with working binaries!

https://www.npmjs.com/package/fbx2gltf/v/0.9.7-p1
