### ISSUE TITLE
v0.9.7 not correctly export uv2 channel

### ISSUE THREAD

**Issue by kevinshane** [facebookincubator/FBX2glTF#223]
Please allow me to open this new issue base for this #169, which is exactly the same problem.
The v0.9.0 correctly export the uv2 lightmap channel for a .glb format, but the latest v0.9.7 is not, it shows only the uv1 channel(which is the diffuse map channel), am I miss something important? Please let me know. Thank you guys!

here is the powershell command:
`.\FBX2glTF-windows-x64.exe -k uv0 -k uv1 -k position -k normal -k color -k binormal -i .\tab.fbx -o table -b -v`

Oh btw, the exported fbx size is different when using different 3ds max, does anyone know what causing the fbx size becomes larger than 3ds max 2014?
size exported in max2014: 16MB
size exported in max2019-2020: 25MB

Thanks

**Comment by zellski** [comment]
@kevinshane do you by any chance have a test FBX that demonstrates the problem? it's very time consuming for me to try to create test assets with my almost non-existent Blender skills.

**Comment by kevinshane** [comment]
hi @zellski , by adding `--no-flip-v` solved the problem ^^
