### ISSUE TITLE
It seems that fbx2gltf cann't run at ubuntu14.04

### ISSUE THREAD

**Issue by xiazhibin** [facebookincubator/FBX2glTF#234]
I download the latest release version [FBX2glTF-linux-x64](https://github.com/facebookincubator/FBX2glTF/releases/download/v0.9.7/FBX2glTF-linux-x64)。And run at ubuntu14.04 got this error:
```
 relocation error: ./FBX2glTF: symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

I try to update the libstdc++.so, but seems that doesn't work

**Comment by zellski** [comment]
Hi, yes, this doesn't surprise me. There may be a way around it by installing just the right version of libstdc++, but honestly I don't remember the details. I spent considerable time last summer (2018) trying to get things to run using very old compilers and whatnot. This may or may not be the same problem.

At the time I basically said I am only going to support Ubuntu 16 and higher; there's just too much frustrating pain involved in trying to support older. Are you in a situation where you could easily switch to a more modern platform?

**Comment by xiazhibin** [comment]
@zellski Thanks for you response.Maybe I will update my platform
