### ISSUE TITLE
converts without correct path to texture

### ISSUE THREAD

**Issue by grzesiekmq** [facebookincubator/FBX2glTF#237]
I run command `.\FBX2glTF-windows-x64.exe -e .\SuperSport_max.fbx`
but it converts single gltf with this issue: 
> Missing texture: bumpbee.jpg

as I check with gltf viewer
but the texture exists in .\

**Comment by grzesiekmq** [comment]
ok I found I missed dragging to gltf viewer the texture files

**Comment by zellski** [comment]
You can also send in the -b flag which creates a single standalone file.
