### ISSUE TITLE
Segmentation fault (macOS)

### ISSUE THREAD

**Issue by supermoos** [facebookincubator/FBX2glTF#24]
When downloading the Darwin (macOS) binary i get a 'Segmentation fault' when trying to convert an FBX file.

```
Defaulting to --pbr-metallic-roughness material support.
Loading FBX File: /my-fbx.fbx
node 0: /RootNode
node 1: /RootNode/scene
node 2: /RootNode/scene/xxxx
node 3: /RootNode/scene/xxxx
node 4: /RootNode/scene/xxxx
node 5: /RootNode/scene/xxxx
node 6: /RootNode/scene/xxxx
node 7: /RootNode/scene/xxxx
node 8: /RootNode/scene/xxxx
node 9: /RootNode/scene/xxxx
node 10: /RootNode/scene/xxxx
mesh 0: xxxx (skinned: NO)
mesh 1: xxxx (skinned: NO)
mesh 2: xxxx (skinned: NO)
mesh 3: xxxx (skinned: NO)
mesh 4: xxxx (skinned: NO)
[1]    962 segmentation fault  ./FBX2glTF /my-fbx.fbx
```

Note, I obscured my layer names to xxxx.

Also, before I could run the command: .`/FBX2glTF /my-fbx.fbx -v` I had to modify the Darwin executable like so:` chmod u+x ./FBX2glTF`

**Comment by zellski** [comment]
Hey, thanks for the report!

It's hard to debug an unknown FBX just from this output, and I assume you're unable to share the FBX in question. Are those fives meshes the only meshes, do you know? Are there animations?

Would you be willing to try on a simple test-FBX like this one? https://drive.google.com/file/d/0Bx-sWOqRZULFZFJfT2dlQ1VNWWs/view

As for permission flag, I assume you downloaded the executable from the 0.9.0 or 0.9.1 release pages? I don't think there's a way to preserve that flag for a download. Perhaps it'd make sense to zip the releases for this reason...

**Comment by supermoos** [comment]
Yeah, sorry I can't. I can tell you though that it's exported from Cinema4d, and if I take the exported c4d FBX, import it to blender 2.79 and export it again as an fbx it works. However running with the `--draco` param gives another segmentation fault. Also, what is the correct way to use the` --keep-attribute` param, is it `--keep-attribute=position,uv0` - doesn't seem to do anything for file size for me.

**Comment by zellski** [comment]
That's helpful, I'm sure I can find someone to do a Cinema4D export for me to test on. It might be a couple of days, though.

Meanwhile, it looks like --keep-attribute is busted; I'll fix that this morning, as well as double-check the state of Draco compression. Thanks!

**Comment by zellski** [comment]
Hey @supermoos -- did some more digging. I'll have --draco and --keep-attribute fixed shortly, but there seem to be a lot of issues around Cinema4D FBX exports. I downloaded a couple of free ones from TurboSquid, and I've patched one of the things where FBX2glTF was making unwarranted assumptions.

But the next error I'm running into -- and I think maybe this is what's crashing for you, too -- is deep within the FBX SDK's tessellation code itself. From the failure I'm going to guess Cinema4D is outputting degenerate polygons, and the SDK isn't handling it very gracefully.

There's probably some way I could sanitize the mesh before doing the triangulation; I'll play around more later. You may have to use the Blender workaround for now. Meanwhile, I'll put out another patch release shortly, with this morning's fixes.

**Comment by msfeldstein** [comment]
let me know if you need any c4d exports

**Comment by zellski** [comment]
Note to future self; this is the path to the assertion failure, when run against this freely downloadable Cinema4D model: https://www.turbosquid.com/3d-models/bmx-bike-3d-model/1069605

```
    frame #3: 0x00007fffdd090893 libsystem_c.dylib`__assert_rtn + 320
    frame #4: 0x000000010081f700 FBX2glTF`fbxsdk::awLinear::Line::Line(fbxsdk::awLinear::Point const&, fbxsdk::awLinear::Point const&) + 224
    frame #5: 0x000000010081f615 FBX2glTF`fbxsdk::awLinear::Line::Line(fbxsdk::awLinear::Point const&, fbxsdk::awLinear::Point const&) + 37
    frame #6: 0x0000000100834dff FBX2glTF`fbxsdk::pointsAreCollinear(fbxsdk::aw::vector<fbxsdk::awLinear::Point2> const&) + 431
    frame #7: 0x000000010083448a FBX2glTF`fbxsdk::awTess::Tess2dConstrainedTriangulate::triangulate(fbxsdk::aw::vector<fbxsdk::awLinear::Point2> const&, int, fbxsdk::aw::vector<int> const&, fbxsdk::aw::vector<int> const&, bool, fbxsdk::aw::vector<int>&) + 1066
    frame #8: 0x00000001007886bb FBX2glTF`fbxsdk::FbxGeometryConverter::TriangulateMeshInternal(fbxsdk::FbxMesh const*) + 6299
    frame #9: 0x00000001007858e9 FBX2glTF`fbxsdk::FbxGeometryConverter::Triangulate(fbxsdk::FbxNodeAttribute*, bool, bool) + 553
    frame #10: 0x00000001007854cb FBX2glTF`fbxsdk::FbxGeometryConverter::Triangulate(fbxsdk::FbxScene*, bool, bool) + 491
    frame #11: 0x000000010007754e FBX2glTF`LoadFBXFile(raw=0x00007fff5fbfc018, fbxFileName="/Users/zell/models/bmx.fbx", textureExtensions="png;jpg;jpeg") at Fbx2Raw.cpp:1075
```

**Comment by supermoos** [comment]
Random thought, not sure if it can be that. But FBX has support for spline exports, which the GLTF format (to my knowledge) doesn't support. Perhaps strip all splines and output a warning?

Not sure if that helps. But thanks for looking into this so quickly!

**Comment by zellski** [comment]
I have no better idea today than I did back then what it is that's going wrong here. I remain fairly sure it's C4D that's exporting invalid FBX, and there's only so much we can do to work around that.
