### ISSUE TITLE
Crash with the latest version (0.9.2)

### ISSUE THREAD

**Issue by davilovick** [facebookincubator/FBX2glTF#34]
I've just updated to the latest FBX2gltf version (0.9.2), and now this tools crash while is converting to gltf. With the previous version (0.9.1) it works perfectly.
Here you can find a tested FBX model that causes the crash:
https://drive.google.com/open?id=1VPZfDZMM_aNr3hdYKZV2i3HSenNG71ln

Thanks in advance for this incredible tool  :)

Best regards,
David Ávila
WaveEngine Team member
http://www.waveengine.net

**Comment by zellski** [comment]
Hey @davilovick! Thanks for the bug report. Great to have a file to test on. I tried Linux and Mac OS X versions of 0.9.2. and I can't actually duplicate it the crash -- the file converts fine. Did you use the Windows version? I'll have a chance to give it a whirl on my PC later tonight, hopefully that reproduces it.

If you were on Linux or Mac OS X, please let me know, then we have a deeper mystery on our hands...

**Comment by zellski** [comment]
Yep, it crashes on Windows. Bug found & fixed. I'll put out a new patch release in the next few days, but in the meantime I surreptitiously updated the binary of the 0.9.2 release [here](https://github.com/facebookincubator/FBX2glTF/releases/download/v0.9.2/FBX2glTF-windows-x64.exe).

Thanks for the quick & helpful bugreport.

**Comment by davilovick** [comment]
Yeah!
Great works!
