### ISSUE TITLE
skin animation

### ISSUE THREAD

**Issue by yeshihua** [facebookincubator/FBX2glTF#37]
FBX2glTF support skin animation, why do I turn over 3ds max2017 fang binxing, after converted into GLTF didn't see the model on the cesium, but no skin animation model can show, but some became transparent like model. Why is that? Is it something to pay attention to when saving FBX?

**Comment by zellski** [comment]
Hi — it might depend on how the FBX was exported, yes. But it should not usually be transparent. What does fang binxing mean?

Are you able to link me the FBX in question? Or at least run the binary with the -v flag and paste the output?

**Comment by yeshihua** [comment]
[a.zip](https://github.com/facebookincubator/FBX2glTF/files/1460484/a.zip)
I am sorry, my English is not good, fang binxing is a software translation error, that no meaning,I do not know why I can only upload this, you look at this fbx any problems.

**Comment by zellski** [comment]
Hey -- look -- it converts okay for me, and seems fine in the BabylonJS viewer (http://sandbox.babylonjs):

![image](https://user-images.githubusercontent.com/714167/32649133-c4d1d15e-c5ad-11e7-9bc4-3cf3ca6e0c82.png)

Maybe it's the Cesium loader that's incomplete?

**Comment by yeshihua** [comment]
Could you please send the file you converted? I would like to try cesiumjs not to load and see if I can change the problem?

**Comment by zellski** [comment]
Sure --

[A-converted.zip](https://github.com/facebookincubator/FBX2glTF/files/1460642/A-converted.zip)

This contains both a .glb version and a .gltf version in a_out subdirectory.

**Comment by yeshihua** [comment]
thank you
