### ISSUE TITLE
Generating unlit models

### ISSUE THREAD

**Issue by msfeldstein** [facebookincubator/FBX2glTF#38]
We have a flag for --khr-materials-common, but it seems to always generate a commonPhong technique.  Is there a way to have it output technique="CONSTANT"?  Would it be worthwhile to add a --khr-materials-common-constant flag to force it?

**Comment by zellski** [comment]
We actually do generate either constants, lambert or phong, directly depending on what shader the material identifies in the FBX; https://github.com/facebookincubator/FBX2glTF/blob/7f8746f56e018b82b915993b47f9384e2703b652/src/Raw2Gltf.cpp#L439-L447

It's just that in practice nobody seems to ever bother changing the material type at the Maya/Modo level.

We could certainly add an override to the converter, but:
- arguably, if we let authors know this is in their hands, they'll be strongly motivated to fix it themselves;
- if we decide to do so, then at least I wanted to wait for the extension to actually enter the ratification process, or at the very least for the raging discussion to settle.

Thoughts?

**Comment by zellski** [comment]
We now have --khr-materials-unlit on master.
