### ISSUE TITLE
neither texture nor vertex colors

### ISSUE THREAD

**Issue by FreakTheMighty** [facebookincubator/FBX2glTF#39]
I have a low poly model of a car that doesn't appear to convert correctly. I've used assimp to convert to a gltf with separate binary and I'm able to view it in [here](https://gltf-viewer.donmccurdy.com/). The glb generated by FBX2glTF, however, isn't displayed. I've linked the source, the working bin/gltf and the apparently broken glb.

https://storage.googleapis.com/blocker-debug/YellowCar.fbx
https://storage.googleapis.com/blocker-debug/assimp/YellowCar.bin
https://storage.googleapis.com/blocker-debug/assimp/YellowCar.gltf
https://storage.googleapis.com/blocker-debug/FBX2glTF-darwin-x64/YellowCar.glb

```
FBX2glTF version 2.0

$ ~/Downloads/FBX2glTF-darwin-x64 -b --input  YellowCar.fbx --output /tmp/YellowCar --verbose
Defaulting to --pbr-metallic-roughness material support.
Loading FBX File: ./Resources/StageAssets/AssetLibrary/Vehicles/Models/YellowCar.fbx
node 0: /RootNode
node 1: /RootNode/Car_med_A_001
mesh 0: Car_med_A_001 (skinned: NO)
animation 0: Take 001 (0 channels, 0.0 MB)
Building render model...
Material 0: Naranaja  [shading: Phong]
Material 1: Gris 01 [shading: Phong]
Material 2: Vidrio [shading: Phong]
Material 3: Light [shading: Phong]
Material 4: Gris_oscuro con rallas [shading: Phong]
Material 5: Naranaja  [shading: Phong]
Material 6: Black_1 [shading: Phong]
Material 7: Rojo_1 [shading: Phong]
Material 8: Grey [shading: Phong]
   9201 vertices
   5151 triangles
      0 textures
      2 nodes
      9 surfaces
      1 animations
Warning: animation 'Take 001' has zero channels. Skipping.
Warning: surface 0_Car_med_A_001 has neither texture nor vertex colors.
Warning: surface 1_Car_med_A_001 has neither texture nor vertex colors.
Warning: surface 2_Car_med_A_001 has neither texture nor vertex colors.
Warning: surface 3_Car_med_A_001 has neither texture nor vertex colors.
Warning: surface 4_Car_med_A_001 has neither texture nor vertex colors.
Warning: surface 5_Car_med_A_001 has neither texture nor vertex colors.
Warning: surface 6_Car_med_A_001 has neither texture nor vertex colors.
Warning: surface 7_Car_med_A_001 has neither texture nor vertex colors.
Warning: surface 8_Car_med_A_001 has neither texture nor vertex colors.
Wrote 338217 bytes of binary glTF to /tmp/YellowCar.glb.
```

**Comment by zellski** [comment]
Great bug report, thanks. I'll see what's going on. It looks like all the colour factors are being computed as fully transparent.

I should remove that warning, by the way. It's totally valid to have neither texture nor vertex colours and this is a good example of such a model.

**Comment by zellski** [comment]
Oh hey, I had already fixed this -- just didn't do a new release yet. This seems like a pretty nasty bug, so I'll see about doing that as soon as I can.

<img width="769" alt="screenshot 2017-11-13 23 03 49" src="https://user-images.githubusercontent.com/714167/32767220-451297c4-c8c7-11e7-839b-a04f7ea1cc10.png">

**Comment by zellski** [comment]
The windows aren't intended to be transparent, right?

**Comment by FreakTheMighty** [comment]
Hey @zellski thanks for the quick response and the great tool. The picture above looks correct, the windows aren't transparent. When you say its already fixed, do you mean its in `master`, but not built to a release, or that you haven't pushed the fix yet?

**Comment by FreakTheMighty** [comment]
I've confirmed it works on master, thanks for the help!

**Comment by FreakTheMighty** [comment]
@zellski I bumped into what seems like a related display issue. I'm curious if you think the source of the [*not really a problem*] problem is the FBX or in the conversion. Checkout this thread/comment https://github.com/BabylonJS/Babylon.js/issues/3155#issuecomment-344789478

**Comment by zellski** [comment]
@FreakTheMighty -- it's definitely a bug. Or was. Semi-hilariously, I already fixed this one too, just the other day, after spotting those BLEND values in your car model: https://github.com/facebookincubator/FBX2glTF/commit/e73c2f46e2ecba204a98906a8975d3b48228c9e4

If you once again pull from master and recompile, it should be now outputting them all as OPAQUE. And I really will put together that new release shortly.
