### ISSUE TITLE
Error converting FBX with two objects with the same name

### ISSUE THREAD

**Issue by davilovick** [facebookincubator/FBX2glTF#41]
FBX2glTF cannot deal with aa FBX file that contains two objects with the same name. The generated glTF file only import one node, instead of 2.

Maybe a solution is to change the name of each node that has the same name that other object:
Box, Box_01, Box_02, etc..

Here you can find a sample FBX model with two animated cubes with the same name ("Box")
https://drive.google.com/open?id=1IEZGHINDZMvR-hHfDQLC5WsbltcB9XIC

Best regards,
David Ávila Membrives
WaveEngine team member

**Comment by zellski** [comment]
Thanks for opening this issue. This deficiency has irritated me for a while; it's not at all uncommon for FBX to contain duplicate node names, and while I need to double check, I don't believe there is any reason they really **need** to be unique for any part of the conversion process.

The name is currently used to track which node a given mesh is rooted in, as well as, for skinned meshes, the root of the associated skeleton. I think we should be able to switch to integer indexes there, although it will require some at least one new map to track FbxNode->RawNode relationships.

No guarantees on when I will be able to get to this, but it's important enough that I am adding it to the 1.0 release requirement list, which gives it higher priority than most things. Thanks again for pointing it out.
