### ISSUE TITLE
How to keep mesh index consistency among several key frame meshes?

### ISSUE THREAD

**Issue by PsycoTodd** [facebookincubator/FBX2glTF#42]
I am trying to use gltf to store several meshes as the key frame for a animated model. The model is single mesh but each of its pose's mesh are also stored in the file.

So first I get all these meshes aligned and to fbx. And use fbx to gltf converter. However I notice that the accessor of gltf shows more vertices number than the original. For instance' a 8 vertices cube now in gltf has 24 vertices. So seems there is some extra vertices generation.

What is the reason for that?

And the big issue is that the index accessor, although have the same length among the key frames, do not have extract same index value. So the one to one map of index is not maintained.

What should I do to keep index map same among key frames?

Thank you.

**Comment by j-conrad** [comment]
It is most likely 24 vertices because your cube has hard edges (as opposed to one smooth surface). That means each vertex gets split into 3-- one for each side of the cube.
This is very common in game engines like Unity, for example.

**Comment by zellski** [comment]
What @j-conrad said about the 8->24 change.

I answered [here](https://github.com/KhronosGroup/glTF/issues/1152#issuecomment-344692889) but briefly, there's no way for the converter to know that your separate meshes are supposed to be interdependent. It rips them to shreds and puts them together, and in the process identical vertices will be eliminated. So it's quite plausible the final index count will be different between them.

But as stated in that thread, if I understand you correctly, blend shapes / morph targets will do precisely what you're after. Try it!
