### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by zhangjianbao** [facebookincubator/FBX2glTF#44]
![image](https://user-images.githubusercontent.com/6321966/32936932-39beaa38-cbb1-11e7-88c4-7c06173149a0.png)
提示缺少 draco,这个是在哪里配置的?

**Comment by zellski** [comment]
Hello @zhangjianbao -- I believe you simply need to [download and install the command 'git'](https://git-scm.com/download/win) on your machine, and to make sure it's in your PATH. FBX2glTF downloads a whole slew of dependencies from github as part of the build, and it uses the 'git' command to do it.
