### ISSUE TITLE
Preserve Mesh instancing

### ISSUE THREAD

**Issue by davilovick** [facebookincubator/FBX2glTF#45]
glTF allows to have several Nodes sharing the same Mesh.

It would be great if FBX2glTF supports that feature :)
Several FbxNode instances can share the same FbxMesh (obtained by the getMesh() method), but right now the code allways creates a new mesh, instead of using the mesh created before in that cases (File: Fbx2Raw.cpp, line 895)

Best regards,
David Ávila Membrives
Wave Engine team member

**Comment by zellski** [comment]
You're finding some prime bugs, @davilovick! Much appreciated. This is obviously a major deal; instancing is critical. We just never happened to use it in any of our past work, so it never came up. Adding to 1.0 release criteria.

**Comment by davilovick** [comment]
Thanks! Great work
I'm working on integrating glTF as the 3D model pipeline in WaveEngine (www.waveengine.net). And we are dealing the FBX conversion with this awesome tool :)

Best regards!

**Comment by davilovick** [comment]
Here I've created a PR that solves that issue :)
https://github.com/facebookincubator/FBX2glTF/pull/46

**Comment by zellski** [comment]
Fantastic! Celebrating Thanksgiving here at the moment, but thanks so much for the PR; I'll look it over ASAP.

**Comment by zellski** [comment]
Teapots work great! This .fbx however does not:

[fir.zip](https://github.com/facebookincubator/FBX2glTF/files/1509095/fir.zip)

It should look like:
<img width="363" alt="screenshot 2017-11-28 01 01 36" src="https://user-images.githubusercontent.com/714167/33310810-b274e8f6-d3d7-11e7-93ac-179ea920c65c.png">

but instead it looks like:
<img width="345" alt="screenshot 2017-11-27 09 47 32" src="https://user-images.githubusercontent.com/714167/33310821-b8a1ba9c-d3d7-11e7-8fb6-a7fd5a6d7963.png">

Pretty tragic. I'm going to dig in a bit and see I can figure out what's going on.

**Comment by zellski** [comment]
Oh -- of course. It's the node name collision bug again. That's on me to fix.

I'll accept your PR & just do the little stye tweaks myself. Thanks again!
