### ISSUE TITLE
Null entries generated for nodes with invalid rotation matrices

### ISSUE THREAD

**Issue by msfeldstein** [facebookincubator/FBX2glTF#49]
In Modo, if you have an object with a 0% scale, the FBX generates an invalid rotation matrix full of NaN.  I'm not sure if this is an FBX issue, or with the code that parses FBX into the internal format of FBX2glTF, but in any case. we should throw an error, or at least a warning instead of outputting invalid gltf
[LookDownOnLiftedCube.fbx.zip](https://github.com/facebookincubator/FBX2glTF/files/1528912/LookDownOnLiftedCube.fbx.zip)

**Comment by zellski** [comment]
Fixed in https://github.com/facebookincubator/FBX2glTF/commit/54c3b04fce5c8feb87e06d6037a4199bacda289d!
