### ISSUE TITLE
[bug] Animation does not show in this FBX file. Pepe_Mocap.fbx

### ISSUE THREAD

**Issue by chipweinberger** [facebookincubator/FBX2glTF#53]
[Pepe_Mocap.zip](https://github.com/facebookincubator/FBX2glTF/files/1536671/Pepe_Mocap.zip)

Again, an instance where both your and my converters are exhibiting the same issue but the FBX file works correctly in FBX Review...

Chip

**Comment by davilovick** [comment]
I've tested this FBX mesh in the official Autodesk FBX Viewer and it seems that the skeleton joints are duplicated, and the animation is associated to the other skeleton hierarchy:
![image](https://user-images.githubusercontent.com/1318239/33746327-c033d636-dbbc-11e7-9166-9c5442244bd4.png)

**Comment by zellski** [comment]
Thanks @davilovick. I did spot this myself. This seems peculiar enough a setup that it's not hugely surprising that the model doesn't convert well. I will close this for now.
