### ISSUE TITLE
Half of normals get flipped

### ISSUE THREAD

**Issue by schubboy** [facebookincubator/FBX2glTF#57]
Used the Khronos and ThreeJS GLTF systems/loaders to verify the same behavior in both systems.  
![faucet-khronos](https://user-images.githubusercontent.com/125443/34360049-39616146-ea2b-11e7-9290-738e078fca87.JPG)

Authoring in Max, export to FBX, run the utility, and this started happening (shader set up to show normals direction in world space):
![image](https://user-images.githubusercontent.com/125443/34359973-6c7e2d8a-ea2a-11e7-84bf-b6682e81cdca.png)

In Max, verified normals (as shown below), "reset xform", collapse all modifiers, re-export, and no change.  
![faucet-top-in-max](https://user-images.githubusercontent.com/125443/34359995-b69e9c9c-ea2a-11e7-8033-54678642829b.JPG)

This looks like a bug in the converter, but I cannot figure out what the pattern is.  Perhaps a winding order problem?  Almost looks "axis based" in where it goes wrong.

**Comment by zellski** [comment]
This is perplexing, and I am not certain I'll be able to figure out what's happening without reproducing the issue locally. Is there a version of this FBX, or another one that shows the same problem, that you're at liberty to attach here, or send to me privately?

**Comment by schubboy** [comment]
Hey, sorry I don't know why I didn't get the notification of the reply back on this thread.  Yes, I can send you the FBX, but I can also tell you what "solved it", although I still think there is a bug in the converter.  In 3DSMax, there is a global utilty called "reset xform", which effectively bakes all transform matrices into the vertex locations of the model, so that there is no longer a matrix transform between world space and model space.  When I ran that on all my scene objects and re-exported, the issue was resolved.  So it appears that certain model-space transforms/rotates do not get properly applied to all verts during conversion from FBX to GLTF.

**Comment by schubboy** [comment]
I should also note that I used Blender as a troubleshooting platform during this - I pulled my "faulty" FBX into blender and exported using the Khronos gltf exporter plugin and it was able to do it with no visual errors.  Perhaps Blender bakes transforms in automagically prior to exporting since their plugin is native to blender instead of utilizing the FBXSDK from Autodesk.

**Comment by zellski** [comment]
Very interesting. It seems to me there could be a few different reasons why baking everything into a single static mesh made the problem go away... and the same with the Blender workflow: it could be the FBX import code, as you suggest, or it could be that the model passes through an internal representation on the way from FBX to glTF that automatically sorts out winding order and whatnot.

If you're willing to email the FBX (or a link to it) to par.winzell@alyx.com I would love to take a look!

**Comment by schubboy** [comment]
I will attempt to recreate the world xform now...

**Comment by schubboy** [comment]
I cannot seem to recreate the Max file/situation where this is occurring, I only have the GLTF and .BIN file (from source control history) of the "bad" file, but I don't think that helps because the gltf is post-conversion - so there wouldn't be any clues in those would there?

**Comment by zellski** [comment]
I think there's likely something real going on here, but without a way to reproduce it's quite an uphill battle to work out what. I'm closing this for now, but if you ever come across an FBX that causes this to happen, I'm game. There's no way you were using negative scaling transforms, right?
