### ISSUE TITLE
Improve Node API

### ISSUE THREAD

**Issue by samskivert** [facebookincubator/FBX2glTF#7]
The Node API is currently admirably simple, but with a tiny bit of effort it could achieve greater flexibility while retaining its simplicity. Let's:

 * Modify the scripts to pass their own command line args through to the tool.
 * Modify the scripts to not assume the target file suffix is `.glb`.
 * Name the exported function `convert` instead of `fbx2glb`, since we're not going to assume a GLB is being generated.
 * Allow args to be supplied to the tool via the exported convert function.

**Comment by zellski** [comment]
Fixed in https://github.com/facebookincubator/FBX2glTF/pull/11.
