### ISSUE TITLE
Unable to upload/validate GLB for fYour GLB File has the following errors: The 3D model could not be posted: This model file is invalid.

### ISSUE THREAD

**Issue by mttcrtr** [facebookincubator/FBX2glTF#72]
I get the following errors when trying to validate the GLB created using the converter:

"Your GLB File has the following errors: The 3D model could not be posted: This model file is invalid."

For each of 3 images I get this error:

"Unsupported image type 'gif'"

I exported an FBX through Maya 2016 using JPEG textures and cannot figure where the GIF errors are coming from.

**Comment by zellski** [comment]
Yeah, this is entirely my fault. When a texture fails to resolve (the FBX points to an image file that doesn't exist / the program can't locate) it substitutes a tiny transparent hard-coded image instead. For some reason I chose a transparent GIF. I have a commit pending that makes it a PNG... that will be in the next release.

Meanwhile, can you try running with the --verbose flag and see what the textures are that it looks for and maybe there's some clues in the output why it can't find them?

**Comment by mttcrtr** [comment]
Hi Zellski, I've actually just now been able to get this working by exporting an FBX with the embed media option checked, but I will try running with the verbose flag and see if that gives me any more clue as to why this wasn't working before. Thanks for the help and info about the update!

**Comment by zellski** [comment]
Great, thanks! Embedded is always the safest, because then the FBX SDK is 100% certain to find the textures. When the texture images are separate files, each filename that's in the FBX has to match exactly with what's in the folder next to the .fbx...

I'm closing this now, but thanks for the reminder that GIF is an idiotic thing to embed in a glTF file, and please let me know if there are other issues.

**Comment by zellski** [comment]
Fixed in https://github.com/facebookincubator/FBX2glTF/pull/74 fwiw :)

**Comment by mttcrtr** [comment]
Awesome, thank you for the incredible quick turnaround on this! :)
