### ISSUE TITLE
light and camera export

### ISSUE THREAD

**Issue by electroheadfx** [facebookincubator/FBX2glTF#73]
Hey, I think it doesn't export light and camera yet ?

**Comment by zellski** [comment]
Correct -- lights are not actually in the glTF standard yet (there is an extension in the works). I will look into the possibilities for a solid camera export.

**Comment by electroheadfx** [comment]
great to know, thanks. Yes for camera it would like awesome. I can create lights in code with babylonjs. But with camera its more difficult in acurate animation.

**Comment by zellski** [comment]
Hrm. Actually it looks like all the code is in place to export cameras:

https://github.com/facebookincubator/FBX2glTF/blob/master/src/Fbx2Raw.cpp#L985-L999

Do you by any chance have an FBX that you're able to share, with camera information in it that's not being exported? These things are so much easier to fix if you can reproduce the issue.

**Comment by electroheadfx** [comment]
Hey,
I posted a test with cube:
https://github.com/electroheadfx/glft-test/tree/master/cam
translated with:
FBX2glTF-darwin-x64 -i testcam.fbx -o testcam -b
I test in sandbox by drag'n drop here: http://sandbox.babylonjs.com
thanks

2018-02-24 22:23 GMT+01:00 Pär Winzell <notifications@github.com>:

**Comment by zellski** [comment]
So, as far as I can tell this .glb has a proper camera export:

```
  "cameras": [
    {
      "name": "",
      "type": "perspective",
      "perspective": {
        "znear": 0.00100000004749745,
        "zfar": 100,
        "aspectRatio": 1.5,
        "yfov": 0.698131680488586
      }
    }
  ],
```

What is it that makes you believe the camera is not being exported, or is incorrectly exported?

**Comment by electroheadfx** [comment]
pefect, so Its from my side to use this camera. Thanks!

2018-02-26 3:38 GMT+01:00 Pär Winzell <notifications@github.com>:

**Comment by zellski** [comment]
everyone loves a happy ending! good luck. :)
