### ISSUE TITLE
[Crash][0.9.4][Windows] Program has stopped responding

### ISSUE THREAD

**Issue by VoidFletcher** [facebookincubator/FBX2glTF#86]
Attempting to execute 

`FBX2glTF-windows-x64.exe "C:\Users\VoidFletcher\Documents\EterniumBottle\eterniumbottles.fbx" -b`

results in a crash as seen below. This issue is not present in version 0.9.3

![image](https://user-images.githubusercontent.com/10835605/37589321-8e58321e-2b6d-11e8-98df-5ebf5c125758.png)

**Comment by zellski** [comment]
That’s unpleasant. I wonder if your model contains some feature that’s not so common? I haven’t heard of a crashing bug previously. Is there any chance you’re able to share a FBX that is exhibits this behaviour?

**Comment by znebby** [comment]
I am having the same issue. Created some primitives with blender. 
[cube2.zip](https://github.com/facebookincubator/FBX2glTF/files/1829381/cube2.zip)

**Comment by zellski** [comment]
I’ll take a look ASAP and push out a new release if I find the bug.

**Comment by zellski** [comment]
I have found & fixed this issue and will make a release ASAP.
