### ISSUE TITLE
There are any wrong in fbx 7.5?

### ISSUE THREAD

**Issue by light564** [facebookincubator/FBX2glTF#87]
my fbx model
https://alphax-bucket.oss-cn-hangzhou.aliyuncs.com/3dmodel/9ed203fa-9bb5-49bf-9f28-47b65db7ed22/miku-GokuRakuJoudo.fbx

**Comment by zellski** [comment]
Hello,

I don't understand what you are asking, but I did run the converter on the FBX you supplied, and it seems to hang/freeze indefinitely. Unfortunately it's not my code that's broken, but the FBX SDK (which is written by Autodesk):

It looks like it spins forever trying to do something with normals. I'm not sure there's anything I can do to fix this.

I see that this is a C4D export. I've seen those be problematic in the past. I think C4D sometimes exports broken FBX. Are you able to load it anywhere else?


```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x000000010080cb5d FBX2glTF`fbxsdk::FbxArray<int>::Find(int const&, int) const + 125
    frame #1: 0x0000000100757430 FBX2glTF`fbxsdk::FbxMesh::ConformNormalsTo(fbxsdk::FbxMesh const*) + 2032
    frame #2: 0x0000000100526fae FBX2glTF`fbxsdk::FbxReaderFbx7_Impl::RebuildTargetShapes(fbxsdk::FbxScene&) const + 4286
    frame #3: 0x000000010051fba0 FBX2glTF`fbxsdk::FbxReaderFbx7::Read(fbxsdk::FbxDocument*, fbxsdk::FbxIO*) + 5456
    frame #4: 0x000000010051e5c7 FBX2glTF`fbxsdk::FbxReaderFbx7::Read(fbxsdk::FbxDocument*) + 327
    frame #5: 0x00000001002e05fd FBX2glTF`fbxsdk::FbxImporter::ImportProcess(fbxsdk::FbxDocument*) + 285
    frame #6: 0x00000001002e2906 FBX2glTF`fbxsdk::FbxImporter::Import(fbxsdk::FbxDocument*, bool) + 54
    frame #7: 0x00000001000a783b FBX2glTF`LoadFBXFile(raw=0x00007ffeefbfb008, fbxFileName="/Users/zell/miku-GokuRakuJoudo.fbx", textureExtensions="png;jpg;jpeg") at Fbx2Raw.cpp:1405
```

**Comment by zellski** [comment]
I'm going to regretfully declare Cinema4D's weird exports only partially supported, and close this.
