### ISSUE TITLE
mark up the original material of exported materials

### ISSUE THREAD

**Issue by zellski** [facebookincubator/FBX2glTF#88]
It wouldn't hurt to drop a field into the 'extras' of each glTF material, giving a little information about where that material came from. Perhaps something like:
```
  "extras": {
    "FromFBX": {
      "fbxMaterialID": "phong",
      "isTruePBR": false,
    }
  }
```

Thoughts? @BKcore?

**Comment by BKcore** [comment]
The important bit for us is whether the material was authored in a proper PBR environment or not (basically whether we can trust the roughness/metalness values).

Would `fbxMaterialID` expose a technique name or a material name? Where would this be coming from?

**Comment by zellski** [comment]
In the FBX SDK, every material has a 'ShadingModel' property. It's a string, not an enum, so theoretically it could contain anything, but in practice the blessed values are Constant, Lambert, Blinn, and Phong. For any material of this type, we'd copy this string into `fbxMaterialID` (actually `shadingModel` might be a better term) and set `isTruePBR` to false.

The **only** FBX material that we'd flag `isTruePBR` as true for is where we detect a Stingray PBS export -- which is is poorly supported by the SDK, but **is** valid FBX, and, importantly, carries the full proper suite of Metallic/Roughness properties.

So, new proposal:
```
  "extras": {
    "FromFBX": {
      "shadingModel": ("Constant"|"Lambert"|"Blinn"|"Phong"|"MetallicRoughness"),
      "isTruePBR": bool,
    }
  }
```

So here `isTruePBR` is entirely derived from `shadingModel`, but I think it's still worthwhile to keep a distinct simple boolean. We may add values to `shadingModel` in the future, but a boolean always stays the same.

**Comment by BKcore** [comment]
I'd nitpick on the capitalization of `FromFBX`, but other than that it sounds good to us.

**Comment by zellski** [comment]
Yeah, good call.

**Comment by zellski** [comment]
Fixed it https://github.com/facebookincubator/FBX2glTF/commit/e992aac1d93fdea60ad2534c3285686f54da1a13
