### ISSUE TITLE
Clarify texture filesystem lookup

### ISSUE THREAD

**Issue by zellski** [facebookincubator/FBX2glTF#9]
- Improve and validate the tricks we already use to match a texture file as listed in the FBX with what exists in the local filesystem.
- If inferring the local file fails, warn explicitly and don't try to read anything later on.
- Extend RawTexture with another field; it should have `name` (logical texture name), `fbxFilename` (the original filename, usually an absolute path on the model author's machine), and `localFilename`, a path that's guaranteed to exist on the local file system.
- In non-binary mode, we bizarrely just add '.ktx' to the texture name, which is certainly guaranteed to be forever wrong. As @robertlong says in the comments, we should copy source files into the output directory and reference them by basename, i.e. as relative path.

**Comment by robertlong** [comment]
@zellski are you currently working on this? I'd be interested in contributing to this as it would allow us to export valid .gltf files with external images. The AFrame community is in need of a better way of exporting from Maya and this project is fairly close.

**Comment by robertlong** [comment]
The non-binary support would be nice. Currently it just outputs a uri with `textureName.ktx`. Instead what is needed is copying the image file into the output directory and setting the proper uri. That would enable `.gltf` export that references images via uri.

**Comment by zellski** [comment]
Oh, yes -- that .ktx line is a bizarre holdover from a very early version. I think we agree that leaning on relative paths by simply outputting the basename of the texture's FBX-internal filename should do what you're looking for. We could possibly copy the texture files too.

I'll take a pass at the cleanup in the next day or two, then we can see where we're at; if there is further work you'd like to see at that point, contributions are more than welcome!

**Comment by robertlong** [comment]
That would be great, thanks!

**Comment by zellski** [comment]
@robertlong Take a look at https://github.com/facebookincubator/FBX2glTF/pull/16 and see what you think.
