### ISSUE TITLE
Mesh triangulation problem

### ISSUE THREAD

**Issue by davilovick** [facebookincubator/FBX2glTF#90]
Hi @zellski 

We have found a fbx model that cause problems in mesh generation:
![image](https://user-images.githubusercontent.com/1318239/37963053-6c377a22-31bd-11e8-9b93-5f731e1e8af2.png)

Currently I cannot spend time trying to fix this problem :(, so I've attached the file:
https://drive.google.com/open?id=1P1P_s8MfW6aGA5Mar2An7fJartmVf5Pb

I try with the --long-indices options and the result are the same :\

Best regards and thanks for this awesome tool :)

**Comment by zellski** [comment]
Peculiar. FBX Review loads it properly (not surprising, that's a very reliable and sturdy app), and has it at 115460 polygons. FBX2glTF only sees 63736 triangles, and yet 188069 vertices.

I'll dig in a bit. Thanks.

**Comment by zellski** [comment]
Hey @davilovick:

- The FBX SDK gives up trying to triangulate this. It just returns NULL with no further insight into what went wrong.
- Blender freezes for like a minute trying to import it, then gives up.
- Assimp, however, can read it and perfectly converted it to a .dae 

So, I don't know if there's a bug in the SDK, or if assimp just tries harder, or if it might even just be outputting the underlying quads directly to the .dae.

I'm keeping this open & hope to investigate further, but lower priority than some other things (including your PR.)

**Comment by davilovick** [comment]
Yes, this is a weird FBX file :)
If you import in 3ds max and reexport again to FBX, there problem is fixed. 
This model send us one customer and he does not know how this file has been created (wich tool or options).

Best regards

**Comment by zellski** [comment]
I'm wondering if I should just implement my own triangulation.

**Comment by zellski** [comment]
@maximcapra Have you found this to happen for any one product in particular?
