### ISSUE TITLE
Version hardcoded to 2.0?

### ISSUE THREAD

**Issue by donmccurdy** [facebookincubator/FBX2glTF#92]
When I run `fbx2gltf --version`, I was expecting to see `0.9.5` but it it appears hardcoded to 2.0. Is this string intended to match the glTF version going forward?

**Comment by zellski** [comment]
Yikes. How embarrassing. I'll fix shortly. Thanks!

**Comment by zellski** [comment]
Finally got around to this in https://github.com/facebookincubator/FBX2glTF/commit/e178a75be3b9727effbb41995a1888969cb25bf0.
