### ISSUE TITLE
Occasional segfault on particular version of FBX file

### ISSUE THREAD

**Issue by donmccurdy** [facebookincubator/FBX2glTF#93]
Cross-filing from https://github.com/mrdoob/three.js/issues/13786, which has two FBX files in this zip: https://github.com/mrdoob/three.js/files/1883878/scene.zip

The version of the file in the `scene1_max` folder (created by 3ds max) works fine, no issues. The version in `scene1` sometimes works, and sometimes segfaults. 

Original issue is solved, but filing in case this is of any use in debugging. :)

**Comment by zellski** [comment]
Thank you! Hopefully it's something I screwed up, rather than the FBX SDK which is largely out of my hands. I'll dig in ASAP!

**Comment by zellski** [comment]
```
Looking up MeshData #371
Looking up MeshData #373
Looking up MeshData #375
Looking up MeshData #-4619574015776784384
```
Well, that looks suspicious. I'll dig in -- thank you, and apologies for the radio silence!

**Comment by zellski** [comment]
This should be fixed in https://github.com/facebookincubator/FBX2glTF/commit/3c8cad47302baf00feadc3f1c9fba6a9c3aaacef. That was a pretty deep cut, and I suspect there are similar bugs still there. Thanks!

**Comment by donmccurdy** [comment]
Great, thank you! :)
