### ISSUE TITLE
Windows installer doesn't work on my pc.

### ISSUE THREAD

**Issue by selflash** [facebookincubator/FBX2glTF#94]
Hi.
I'm trying to install FBX2glTF on my pc.
So, I downloaded FBX2glTF-windows-x64.exe v0.9.5 and double clicked .exe.
but it doesn't work.
A black screen will appear for a moment and it will end.
My pc is windows10.
Could you help me to work it on my pc?
I can work FBX2glTF on my mac completely but doesn't work on windows pc. why??
thanks.

**Comment by selflash** [comment]
Perhaps, does it needs to install Visual Studio 2017?    2015 is installed but 2017 is not.

**Comment by zellski** [comment]
@selflash Hello, thanks for your feedback! The Windows version is not an installer. It doesn't have any UI at all. It's just a command line utility, exactly like the Mac and Linux versions.

To run it, you just type the name of the application into a command prompt, such as:

```
 > FBX2glTF --binary --draco --verbose \
          --input ~/models/source/butterfly.fbx \
          --output ~/models/target/butterfly.glb
```

**Comment by selflash** [comment]
I've been able to make it work.
I found out the Japanese article and did in this way.

https://developers.facebook.com/docs/sharing/3d-posts/glb-tutorials

In windows, I needed to write "FBX2glTF-windows-x64.exe", not "FBX2glTF".
I think it's better you add explaining to README.md in order to work on windows for windows users.
Thanks!
