### ISSUE TITLE
Conversion crashing when using non-binary mode

### ISSUE THREAD

**Issue by Rayfoundry** [facebookincubator/FBX2glTF#95]
When converting the attached FBX without the -b option, the converter segvaults after warning of an unsupported "eInheritRrSs" transform.

Converting with -b option works flawless.

[crash.zip](https://github.com/facebookincubator/FBX2glTF/files/1923111/crash.zip)

**Comment by zellski** [comment]
Thanks! Will investigate ASAP.

**Comment by Rayfoundry** [comment]
Hi, thank you. Haven't built from source yet. I'll try.

Attached you find a very simple file (cylinder) that crashes fbx2gltf even when binary mode is enabled. The only solution for now with the current release is to generate it draco mesh compressed. I assume, that draco reshuffles the vertices somehow? Anyway, I hope the file helps tracking down the bug.

[Cylinder](https://s3-eu-west-1.amazonaws.com/rayfoundry-tmp/mesh_CylinderA_LO.fbx)

**Comment by zellski** [comment]
I'm glad to say your cylinder converts fine, with recent commits (I am not sure which one exactly your model was triggering). I'll get a new release out, soon. I'm hoping to get a few more fixes and improvements in.
