### ISSUE TITLE
THREE.PropertyBinding: Trying to update property for track: Obj_JN0_1.scale but it wasn't found.

### ISSUE THREAD

**Issue by haolly** [facebookincubator/FBX2glTF#99]
I use this tool to convert my fbx to gltf, when played in three.js , the error occurs.
But the origin fbx file has **Obj_JN0_1** when I import it in unity, I can see it.
So there may be a something wrong in the converter

**Comment by haolly** [comment]
My fault

**Comment by mikebourbeauart** [comment]
@haolly what did you do wrong? I'm getting a similar error: "Trying to update property for track: RIGspine_02_02.position but it wasn't found."

**Comment by elendee** [comment]
me too, working fbx animation, but same error message upon trying to play the anim in three

**Comment by zellski** [comment]
@elendee So just to make sure - your issue is resolved, it was a JavaScript logic error on your end that you've since fixed?

**Comment by elendee** [comment]
@zellski yea, and if possible I would change the error to `tried to update property on object, but it is not a valid track`, that would clue people in a little faster.  Might be more trouble than it's worth though

**Comment by zellski** [comment]
@elendee Agreed, but that error message doesn't come from this tool in any way; it's from the [three.js](https://github.com/mrdoob/three.js/) web browser 3D library. You could conceivably file an issue there...

**Comment by elendee** [comment]
ah! - this thread came up at the top of a Google search and I assumed it was for three.js, that's whooops...

**Comment by zellski** [comment]
No worries :-) the glTF world is pretty small!

**Comment by stiegosaurus** [comment]
> me too, working fbx animation, but same error message upon trying to play the anim in three. [solved] correct: `let mixer = new THREE.AnimationMixer( obj.scene );` incorrect: `let mixer = new THREE.AnimationMixer( obj );`

Thank you! Was sitting here tinkering for a while trying to figure out why Three.JS was barking that error! Cheers

**Comment by Oumer1234** [comment]
THREE.PropertyBinding: Trying to update node for track: mixamorigHips.position but it wasn't found.
